### ISSUE TITLE
Horizontal rules break frontmatter parsing

### ISSUE THREAD

**Issue by Athrunen** [kevboh/longform#100]
The file

```
---
tags:
  - draft
last_review: 2022-09-04
review_frequency: 5
topics:
  - opinion
type: article
focus: work
longform:
  format: scenes
  workflow: Default Workflow
  sceneFolder: /
  scenes: []
  ignoredFiles: []
---

some text

---

some text
```

fails to parse with

```
Uncaught (in promise) YAMLParseError: Source contains multiple documents; please use YAML.parseAllDocuments() at line 15, column 1:

  ignoredFiles: []
---
^

    at bv.onDocument (app.js:1:708951)
    at bv.end (app.js:1:687541)
    at app.js:1:709049
    at Fv (app.js:1:709130)
    at Module.mR (app.js:1:1535571)
    at eval (plugin:longform:20573:25)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:longform:28:58)
```

This only occurs in files with longform frontmatter and only when longform is enabled. Obsidian is v0.15.9, longform is 2.0 through BRAT.
Replacing `---` with `***` or `___` works around this for now.
This may be related to #87
