### ISSUE TITLE
Ignoring file through ignore dialogue cuts content between horizontal rules

### ISSUE THREAD

**Issue by Athrunen** [kevboh/longform#108]
Might be a remnant of #100 and can be replicated using the same example file. The end result is essentially:

```
---
longform:
  format: scenes
  workflow: Default Workflow
  sceneFolder: /
  scenes: []
  ignoredFiles:
    - file
--- <- There was "some text" here

some text
```
