### ISSUE TITLE
Can't Add Scenes to Project

### ISSUE THREAD

**Issue by egoebelbecker** [kevboh/longform#119]
When I try to add a file to my project the GUI indicates that it's there, but it's not added to Index.md 

I see this on the console:

```
node:internal/errors:464 Uncaught (in promise) TypeError: The "path" argument must be of type string. Received null
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.join (node:path:1172:7)
    at e.getFullRealPath (app.js:1:1072141)
    at e.getFullPath (app.js:1:1072064)
    at app.js:1:1063785
    at n (app.js:1:1072467)
```

Here the Index file:

```
longform:
  format: scenes
  title: The Great War of the Worlds
  sceneFolder: /
  scenes: []
  ignoredFiles: []
```

This is on Both macOS Monterey and Ubuntu Linux.
