### ISSUE TITLE
Docs: Add annotated CSS snippet for .longform-leaf

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#12]
I wanted to try out some custom css for the notes in a longform project. This is one of the things I tried:
```css
.longform-leaf {
	font-family: "Garamond";
	font-size: 2em;
}
```
strangely enough, changing the font family works without any problems, while changing the font size does not have any effect. I also tried `px`and `%`, both with no effect. With other css items, I can change the font-size without any issue. Is the font-size maybe somehow overwritten by the longform plugin?

Also, as someone with little CSS knowledge, maybe some guidance would help. Even with experimenting with changing `.longform-leaf .suggestion-item.is-selected` and `.longform-leaf .view-header`, I could not figure out what those two actually do?

One solution would be to simply offer some commented example css snippets. They could also be used by people without any css-knowledge as a small selection of ready-made snippets to choose from.

**Comment by kevboh** [comment]
`.longform-leaf` isn't styled by the plugin at all—it's just added and removed to app panes, intended to be set with css snippets. I'm not sure why font-size isn't working, but I suspect it has to do with the way Obsidian styles text.

I just checked my own personal snippet, and I'm doing:

```
.longform-leaf .markdown-source-view {
  font-size: 1.2rem;
  text-indent: 2rem;
}
```

So I'd try that.

I can add annotated snippets if helpful. I think styling Obsidian is kind of a matter of spelunking in the dev tools right now, which requires a decent understanding of the DOM and CSS, unfortunately.

**Comment by kevboh** [comment]
I'm renaming this to more accurately describe the task of adding an annotated snippet, as there's no bug in Longform here.

**Comment by chrisgrieser** [comment]
> `.longform-leaf` isn't styled by the plugin at all—it's just added and removed to app panes, intended to be set with css snippets. I'm not sure why font-size isn't working, but I suspect it has to do with the way Obsidian styles text.
> 
> I just checked my own personal snippet, and I'm doing:
> 
> ```
> .longform-leaf .markdown-source-view {
>   font-size: 1.2rem;
>   text-indent: 2rem;
> }
> ```
> 
> So I'd try that.
> 
> I can add annotated snippets if helpful. I think styling Obsidian is kind of a matter of spelunking in the dev tools right now, which requires a decent understanding of the DOM and CSS, unfortunately.

ah, I found the issue. `.longform-leaf` is not the proper css target, you have to target preview and editor explicitly. The following code works:
```css
.longform-leaf .markdown-preview-view,
.longform-leaf .cm-s-obsidian {
	font-size: 1.1em;
}
```

**Comment by chrisgrieser** [comment]
Here is my longform css, feel free to add it to the documentation as an example if you like.

```css
/* longform font */
.longform-leaf .markdown-preview-view,
.longform-leaf .cm-s-obsidian {

	/* justify all text and use hypenation */
	text-align: justify;
	hyphens: auto;

	/* change font style */
	font-family: "Garamond";
	font-size: 1.1em;

	/* indention (at the left side) */
	text-indent: 2rem;
}
```
