### ISSUE TITLE
Nothing works?

### ISSUE THREAD

**Issue by gernalix** [kevboh/longform#17]
Whatever I click on scenes, drafts, compile, nothing happens.
![X4GnrevRLF](https://user-images.githubusercontent.com/22417984/129091279-51b4f4f3-4902-49ba-a7dd-70ead6c1dcbf.gif)

**Comment by gernalix** [comment]
[Index.md](https://github.com/kevboh/longform/files/6970928/Index.md)
I'm using v 1.0.3

**Comment by kevboh** [comment]
@gernalix in the meantime, try:

1. Unmarking the project (or clicking the reset button in Longform settings)
2. Restarting Obsidian.
3. Deleting the Index file.
4. Marking the project again.

**Comment by kevboh** [comment]
Alternatively, you can replace the frontmatter in Index.md with

```
---
version: 1
drafts:
  - name: Draft 1
    folder: Draft 1
    scenes: []
---
```

Assuming the folder in your project is named `Draft 1`.
