### ISSUE TITLE
Feature Request: Arbitrary Scene Organization

### ISSUE THREAD

**Issue by b-camphart** [kevboh/longform#184]
**Describe the solution you'd like**
I'd like to be able to organize scenes into, for example, acts

**Describe alternatives you've considered**
Right now, I have to create empty files in the scene folder called "Act One" or whatever.  I tried faking it without adding the files, but still modifying the scenes property to have nonexistent headers:
```yaml

longform:
  scenes:
    - Act One
    - - Scene 1
    - - Scene 2
    - Act Two
    - - Scene 3
    - - Scene 4
```
But the result of this, without the "Act One" and "Act Two" files existing, is that longform just outright ignores them.
