### ISSUE TITLE
Feature Request: Add  icon in front of the file name based on the yaml value

### ISSUE THREAD

**Issue by wwjCMP** [kevboh/longform#221]
Add an icon in front of the file name based on the yaml value. 
For example, in file 1
---
status: done
---

🎉file 1 name
file name 2

**Comment by kevboh** [comment]
Just to clarify, do you mean in front of scenes in the Longform pane, or in front of notes in the Obsidian file explorer?

**Comment by kevboh** [comment]
If the former, I could see it, although it seems pretty niche; if the latter, not in scope for this plugin.

**Comment by kevboh** [comment]
This will be added in the next commit. It only works for the `status` property. This CSS snippet will add your example:

```css
[data-scene-status="done"]::before {
  content: "🎉";
  padding: 0 4px 0 0;
}
```
